# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import petugas_pb2 as petugas__pb2


class PetugasServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/petugas.PetugasService/List',
                request_serializer=petugas__pb2.PetugasListRequest.SerializeToString,
                response_deserializer=petugas__pb2.PetugasListResponse.FromString,
                )
        self.Detail = channel.unary_unary(
                '/petugas.PetugasService/Detail',
                request_serializer=petugas__pb2.PetugasDetailRequest.SerializeToString,
                response_deserializer=petugas__pb2.PetugasDetailResponse.FromString,
                )
        self.Create = channel.unary_unary(
                '/petugas.PetugasService/Create',
                request_serializer=petugas__pb2.PetugasCreateRequest.SerializeToString,
                response_deserializer=petugas__pb2.PetugasCreateResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/petugas.PetugasService/Update',
                request_serializer=petugas__pb2.PetugasUpdateRequest.SerializeToString,
                response_deserializer=petugas__pb2.PetugasUpdateResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/petugas.PetugasService/Delete',
                request_serializer=petugas__pb2.PetugasDeleteRequest.SerializeToString,
                response_deserializer=petugas__pb2.PetugasDeleteResponse.FromString,
                )
        self.Login = channel.unary_unary(
                '/petugas.PetugasService/Login',
                request_serializer=petugas__pb2.PetugasLoginRequest.SerializeToString,
                response_deserializer=petugas__pb2.PetugasLoginResponse.FromString,
                )
        self.Logout = channel.unary_unary(
                '/petugas.PetugasService/Logout',
                request_serializer=petugas__pb2.PetugasLogoutRequest.SerializeToString,
                response_deserializer=petugas__pb2.PetugasLogoutResponse.FromString,
                )


class PetugasServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Detail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PetugasServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=petugas__pb2.PetugasListRequest.FromString,
                    response_serializer=petugas__pb2.PetugasListResponse.SerializeToString,
            ),
            'Detail': grpc.unary_unary_rpc_method_handler(
                    servicer.Detail,
                    request_deserializer=petugas__pb2.PetugasDetailRequest.FromString,
                    response_serializer=petugas__pb2.PetugasDetailResponse.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=petugas__pb2.PetugasCreateRequest.FromString,
                    response_serializer=petugas__pb2.PetugasCreateResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=petugas__pb2.PetugasUpdateRequest.FromString,
                    response_serializer=petugas__pb2.PetugasUpdateResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=petugas__pb2.PetugasDeleteRequest.FromString,
                    response_serializer=petugas__pb2.PetugasDeleteResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=petugas__pb2.PetugasLoginRequest.FromString,
                    response_serializer=petugas__pb2.PetugasLoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=petugas__pb2.PetugasLogoutRequest.FromString,
                    response_serializer=petugas__pb2.PetugasLogoutResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'petugas.PetugasService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PetugasService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/petugas.PetugasService/List',
            petugas__pb2.PetugasListRequest.SerializeToString,
            petugas__pb2.PetugasListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Detail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/petugas.PetugasService/Detail',
            petugas__pb2.PetugasDetailRequest.SerializeToString,
            petugas__pb2.PetugasDetailResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/petugas.PetugasService/Create',
            petugas__pb2.PetugasCreateRequest.SerializeToString,
            petugas__pb2.PetugasCreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/petugas.PetugasService/Update',
            petugas__pb2.PetugasUpdateRequest.SerializeToString,
            petugas__pb2.PetugasUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/petugas.PetugasService/Delete',
            petugas__pb2.PetugasDeleteRequest.SerializeToString,
            petugas__pb2.PetugasDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/petugas.PetugasService/Login',
            petugas__pb2.PetugasLoginRequest.SerializeToString,
            petugas__pb2.PetugasLoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/petugas.PetugasService/Logout',
            petugas__pb2.PetugasLogoutRequest.SerializeToString,
            petugas__pb2.PetugasLogoutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
