# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kategori.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ekategori.proto\x12\x08kategori\"$\n\x08Kategori\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nama\x18\x02 \x01(\t\"\x1d\n\x0fKategoriRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"8\n\x10KategoriResponse\x12$\n\x08kategori\x18\x01 \x01(\x0b\x32\x12.kategori.Kategori\"\x15\n\x13KategoriListRequest\"<\n\x14KategoriListResponse\x12$\n\x08kategori\x18\x01 \x03(\x0b\x32\x12.kategori.Kategori\"%\n\x15KategoriCreateRequest\x12\x0c\n\x04nama\x18\x01 \x01(\t\"2\n\x16KategoriCreateResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nama\x18\x02 \x01(\t\"1\n\x15KategoriUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nama\x18\x02 \x01(\t\"2\n\x16KategoriUpdateResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nama\x18\x02 \x01(\t\"#\n\x15KategoriDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\")\n\x16KategoriDeleteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xfd\x02\n\x0fKategoriService\x12<\n\x03Get\x12\x19.kategori.KategoriRequest\x1a\x1a.kategori.KategoriResponse\x12\x45\n\x04List\x12\x1d.kategori.KategoriListRequest\x1a\x1e.kategori.KategoriListResponse\x12K\n\x06\x43reate\x12\x1f.kategori.KategoriCreateRequest\x1a .kategori.KategoriCreateResponse\x12K\n\x06Update\x12\x1f.kategori.KategoriUpdateRequest\x1a .kategori.KategoriUpdateResponse\x12K\n\x06\x44\x65lete\x12\x1f.kategori.KategoriDeleteRequest\x1a .kategori.KategoriDeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kategori_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_KATEGORI']._serialized_start=28
  _globals['_KATEGORI']._serialized_end=64
  _globals['_KATEGORIREQUEST']._serialized_start=66
  _globals['_KATEGORIREQUEST']._serialized_end=95
  _globals['_KATEGORIRESPONSE']._serialized_start=97
  _globals['_KATEGORIRESPONSE']._serialized_end=153
  _globals['_KATEGORILISTREQUEST']._serialized_start=155
  _globals['_KATEGORILISTREQUEST']._serialized_end=176
  _globals['_KATEGORILISTRESPONSE']._serialized_start=178
  _globals['_KATEGORILISTRESPONSE']._serialized_end=238
  _globals['_KATEGORICREATEREQUEST']._serialized_start=240
  _globals['_KATEGORICREATEREQUEST']._serialized_end=277
  _globals['_KATEGORICREATERESPONSE']._serialized_start=279
  _globals['_KATEGORICREATERESPONSE']._serialized_end=329
  _globals['_KATEGORIUPDATEREQUEST']._serialized_start=331
  _globals['_KATEGORIUPDATEREQUEST']._serialized_end=380
  _globals['_KATEGORIUPDATERESPONSE']._serialized_start=382
  _globals['_KATEGORIUPDATERESPONSE']._serialized_end=432
  _globals['_KATEGORIDELETEREQUEST']._serialized_start=434
  _globals['_KATEGORIDELETEREQUEST']._serialized_end=469
  _globals['_KATEGORIDELETERESPONSE']._serialized_start=471
  _globals['_KATEGORIDELETERESPONSE']._serialized_end=512
  _globals['_KATEGORISERVICE']._serialized_start=515
  _globals['_KATEGORISERVICE']._serialized_end=896
# @@protoc_insertion_point(module_scope)
