# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rest.grpc_client.anggota.anggota_pb2 as anggota__pb2


class AnggotaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
            "/anggota.AnggotaService/List",
            request_serializer=anggota__pb2.AnggotaListRequest.SerializeToString,
            response_deserializer=anggota__pb2.AnggotaListResponse.FromString,
        )
        self.Get = channel.unary_unary(
            "/anggota.AnggotaService/Get",
            request_serializer=anggota__pb2.AnggotaRequest.SerializeToString,
            response_deserializer=anggota__pb2.AnggotaResponse.FromString,
        )
        self.Create = channel.unary_unary(
            "/anggota.AnggotaService/Create",
            request_serializer=anggota__pb2.AnggotaCreateRequest.SerializeToString,
            response_deserializer=anggota__pb2.AnggotaCreateResponse.FromString,
        )
        self.Update = channel.unary_unary(
            "/anggota.AnggotaService/Update",
            request_serializer=anggota__pb2.AnggotaUpdateRequest.SerializeToString,
            response_deserializer=anggota__pb2.AnggotaUpdateResponse.FromString,
        )
        self.Delete = channel.unary_unary(
            "/anggota.AnggotaService/Delete",
            request_serializer=anggota__pb2.AnggotaDeleteRequest.SerializeToString,
            response_deserializer=anggota__pb2.AnggotaDeleteResponse.FromString,
        )
        self.Login = channel.unary_unary(
            "/anggota.AnggotaService/Login",
            request_serializer=anggota__pb2.AnggotaLoginRequest.SerializeToString,
            response_deserializer=anggota__pb2.AnggotaLoginResponse.FromString,
        )
        self.Logout = channel.unary_unary(
            "/anggota.AnggotaService/Logout",
            request_serializer=anggota__pb2.AnggotaLogoutRequest.SerializeToString,
            response_deserializer=anggota__pb2.AnggotaLogoutResponse.FromString,
        )


class AnggotaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AnggotaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "List": grpc.unary_unary_rpc_method_handler(
            servicer.List,
            request_deserializer=anggota__pb2.AnggotaListRequest.FromString,
            response_serializer=anggota__pb2.AnggotaListResponse.SerializeToString,
        ),
        "Get": grpc.unary_unary_rpc_method_handler(
            servicer.Get,
            request_deserializer=anggota__pb2.AnggotaRequest.FromString,
            response_serializer=anggota__pb2.AnggotaResponse.SerializeToString,
        ),
        "Create": grpc.unary_unary_rpc_method_handler(
            servicer.Create,
            request_deserializer=anggota__pb2.AnggotaCreateRequest.FromString,
            response_serializer=anggota__pb2.AnggotaCreateResponse.SerializeToString,
        ),
        "Update": grpc.unary_unary_rpc_method_handler(
            servicer.Update,
            request_deserializer=anggota__pb2.AnggotaUpdateRequest.FromString,
            response_serializer=anggota__pb2.AnggotaUpdateResponse.SerializeToString,
        ),
        "Delete": grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=anggota__pb2.AnggotaDeleteRequest.FromString,
            response_serializer=anggota__pb2.AnggotaDeleteResponse.SerializeToString,
        ),
        "Login": grpc.unary_unary_rpc_method_handler(
            servicer.Login,
            request_deserializer=anggota__pb2.AnggotaLoginRequest.FromString,
            response_serializer=anggota__pb2.AnggotaLoginResponse.SerializeToString,
        ),
        "Logout": grpc.unary_unary_rpc_method_handler(
            servicer.Logout,
            request_deserializer=anggota__pb2.AnggotaLogoutRequest.FromString,
            response_serializer=anggota__pb2.AnggotaLogoutResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "anggota.AnggotaService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class AnggotaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/anggota.AnggotaService/List",
            anggota__pb2.AnggotaListRequest.SerializeToString,
            anggota__pb2.AnggotaListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Get(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/anggota.AnggotaService/Get",
            anggota__pb2.AnggotaRequest.SerializeToString,
            anggota__pb2.AnggotaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Create(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/anggota.AnggotaService/Create",
            anggota__pb2.AnggotaCreateRequest.SerializeToString,
            anggota__pb2.AnggotaCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Update(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/anggota.AnggotaService/Update",
            anggota__pb2.AnggotaUpdateRequest.SerializeToString,
            anggota__pb2.AnggotaUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Delete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/anggota.AnggotaService/Delete",
            anggota__pb2.AnggotaDeleteRequest.SerializeToString,
            anggota__pb2.AnggotaDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Login(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/anggota.AnggotaService/Login",
            anggota__pb2.AnggotaLoginRequest.SerializeToString,
            anggota__pb2.AnggotaLoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Logout(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/anggota.AnggotaService/Logout",
            anggota__pb2.AnggotaLogoutRequest.SerializeToString,
            anggota__pb2.AnggotaLogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
